const dogsList = [
  {
    id: 1,
    name: "Max",
    breed: "Cocker Spaniel",
    age: 3,
    likes: "playing fetch, swimming",
    color: "Golden",
    height: "24 inches",
    length: "32 inches",
    image: "images/1.jpg",
    gender:"male",
    description:
      "Max is a friendly and energetic Cocker Spaniel. He loves playing fetch and going for long walks.",
  },
  {
    id: 2,
    name: "Buddy",
    breed: "Shih",
    age: 4,
    likes: "running, obedience training",
    color: "Black and Tan",
    height: "26 inches",
    length: "30 inches",
    image: "images/2.jpg",
    gender:"male",
    description:
      "Buddy is a loyal and intelligent Shih. He enjoys running and obedience training.",
  },
  {
    id: 3,
    name: "Daisy",
    breed: "Pomeranian",
    age: 2,
    likes: "swimming, playing with toys",
    color: "Golden",
    height: "22 inches",
    length: "28 inches",
    image: "images/3.jpg",
    gender:"female",
    description:
      "Daisy is a playful and affectionate Pomeranian. She loves swimming and playing with her toys.",
  },
  {
    id: 4,
    name: "Rocky",
    breed: "Norfolk Terrier",
    age: 0.4,
    likes: "sunbathing, eating treats",
    color: "Brown",
    height: "20 inches",
    length: "25 inches",
    image: "images/4.jpg",
    gender:"male",
    description:
      "Rocky is a laid-back and friendly Norfolk Terrier. He enjoys sunbathing and indulging in treats.",
  },
  {
    id: 5,
    name: "Luna",
    breed: "Dalamatian",
    age: 1,
    likes: "sniffing around, cuddling",
    color: "White and Brown",
    height: "18 inches",
    length: "22 inches",
    image: "images/5.jpg",
    gender:"female",
    description:
      "Luna is an inquisitive and affectionate Dalamatian. She loves sniffing around and cuddling with her owner.",
  },
  {
    id: 6,
    name: "Bailey",
    breed: "French Bulldog",
    age: 0.5,
    likes: "playing with toys, grooming",
    color: "White",
    height: "20 inches",
    length: "24 inches",
    image: "images/6.jpg",
    gender:"female",
    description:
      "Bailey is a smart and elegant French Bulldog. She enjoys playing with toys and being groomed.",
  },
  {
    id: 7,
    name: "Sadie",
    breed: "Dandie Dinmont",
    age: 2,
    likes: "chasing squirrels, going for walks",
    color: "Black and Brown",
    height: "24 inches",
    length: "28 inches",
    image: "images/7.jpg",
    gender:"female",
    description:
      "Sadie is a strong and loyal Dandie Dinmont. She enjoys chasing squirrels and going for long walks.",
  },
  {
    id: 8,
    name: "Toby",
    breed: "Dalamatian",
    age: 2,
    likes: "snuggling, barking at strangers",
    color: "Gray and Tan",
    height: "8 inches",
    length: "10 inches",
    image: "images/8.jpg",
    gender:"male",
    description:
      "Toby is a small but feisty Dalamatian. He loves snuggling and barking at strangers.",
  },
  {
    id: 9,
    name: "Molly",
    breed: "Siberian Husky",
    age: 4,
    likes: "playing fetch, getting belly rubs",
    color: "Brindle",
    height: "22 inches",
    length: "26 inches",
    image: "images/9.jpg",
    gender:"female",
    description:
      "Molly is an energetic and affectionate Siberian Husky. She loves playing fetch and getting belly rubs.",
  },
  {
    id: 10,
    name: "Jake",
    breed: "Labrador Retriever",
    age: 3,
    likes: "running, howling",
    color: "Gray and White",
    height: "24 inches",
    length: "30 inches",
    image: "images/10.jpg",
    gender:"male",
    description:
      "Jake is an adventurous Labrador Retriever. He enjoys running and howling at the moon.",
  },
  {
    id: 11,
    name: "Sophie",
    breed: "Golden Retriever",
    age: 2,
    likes: "cuddling, burrowing",
    color: "Brown",
    height: "10 inches",
    length: "15 inches",
    image: "images/11.jpg",
    gender:"female",
    description:
      "Sophie is a playful and affectionate Golden Retriever. She loves cuddling and burrowing under blankets.",
  },
  {
    id: 12,
    name: "Charlie",
    breed: "Border Collie",
    age: 5,
    likes: "napping, gentle giants",
    color: "Fawn",
    height: "30 inches",
    length: "36 inches",
    image: "images/12.jpg",
    gender:"male",
    description:
      "Charlie is a gentle giant and a loyal Border Collie. He enjoys napping and being around people.",
  },
  {
    id: 13,
    name: "Lucy",
    breed: "Shetland Sheepdog",
    age: 0.3,
    likes: "protecting, running",
    color: "Black and Tan",
    height: "26 inches",
    length: "32 inches",
    image: "images/13.jpg",
    gender:"female",
    description:
      "Lucy is a loyal and protective Shetland Sheepdog. She loves running and protecting her family.",
  },
  {
    id: 14,
    name: "Cooper",
    breed: "Labrador Retriever",
    age: 4,
    likes: "grooming, being pampered",
    color: "White and Brown",
    height: "10 inches",
    length: "12 inches",
    image: "images/14.jpg",
    gender:"male",
    description:
      "Cooper is a sweet and affectionate Labrador Retriever. He loves grooming and being pampered by his owner.",
  },
  {
    id: 15,
    name: "Bella",
    breed: "Shih",
    age: 2,
    likes: "playing with toys, chasing birds",
    color: "Salt and Pepper",
    height: "12 inches",
    length: "14 inches",
    image: "images/15.jpg",
    gender:"female",
    description:
      "Bella is an alert and playful Shih. She loves playing with toys and chasing birds.",
  },
  {
    id: 16,
    name: "Chloe",
    breed: "Pug",
    age: 3,
    likes: "cuddling, snuggling",
    color: "Ruby",
    height: "12 inches",
    length: "14 inches",
    image: "images/16.jpg",
    gender:"female",
    description:
      "Chloe is a gentle and affectionate Pug. She loves cuddling and snuggling with her owner.",
  },
  {
    id: 17,
    name: "Riley",
    breed: "Samoyed",
    age: 2,
    likes: "fetching, exploring",
    color: "Cream",
    height: "8 inches",
    length: "10 inches",
    image: "images/17.jpg",
    gender:"male",
    description:
      "Riley is a lively and curious Samoyed. He loves fetching toys and exploring new places.",
  },
  {
    id: 18,
    name: "Lily",
    breed: "Labrador Retriever",
    age: 4,
    likes: "herding, agility training",
    color: "Blue Merle",
    height: "20 inches",
    length: "24 inches",
    image: "images/18.jpg",
    gender:"female",
    description:
      "Lily is an intelligent and active Labrador Retriever. She excels in herding and agility training.",
  },
  {
    id: 19,
    name: "Zoey",
    breed: "Papillon",
    age: 3,
    likes: "chasing, playing with children",
    color: "Sable and White",
    height: "14 inches",
    length: "18 inches",
    image: "images/19.jpg",
    gender:"female",
    description:
      "Zoey is a playful and affectionate Papillon. She loves chasing after toys and playing with children.",
  },
  {
    id: 20,
    name: "Harley",
    breed: "Chihuahua",
    age: 1,
    likes: "chasing frisbees, herding",
    color: "Black and White",
    height: "20 inches",
    length: "24 inches",
    image: "images/20.jpg",
    gender:"female",
    description:
      "Harley is a highly intelligent and energetic Chihuahua. She excels in agility and enjoys herding.",
  },
];

export default dogsList;
